name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
      - run: npm run build --if-present
        env:
          CI: true
